### ISSUE TITLE
Cannot see messages/labels on UI component (e.g. button, labels..) on capture tool

### ISSUE THREAD

**Issue by uehaj2022** [uehaj2022/latteart#4]
**Describe the bug**
Cannot see messages/labels on UI component (e.g. button, labels..) on capture tool

**To Reproduce**
1. Go to capture tool
2. Labels and selections are blank(no meaninful message)

**Expected behavior**
![image](https://user-images.githubusercontent.com/112670104/192928736-6101bd97-8d8b-414f-be94-e75669255dc2.png)

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome?
 - Version Unknown

**Additional context**
-

**Comment by dikshika-s** [comment]
IOS: Windows
Browser: Chrome 

![image](https://user-images.githubusercontent.com/79650403/193242656-2c4bf390-c9fb-470b-b16c-1c5358fd2563.png)

I am getting this error could you please help me resolve it .

**Comment by GochaLearningSpace** [comment]
> **Describe the bug** Cannot see messages/labels on UI component (e.g. button, labels..) on capture tool
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to capture tool
> 2. Labels and selections are blank(no meaninful message)
> 
> **Expected behavior** ![image](https://user-images.githubusercontent.com/112670104/192928736-6101bd97-8d8b-414f-be94-e75669255dc2.png)
> 
> ## **Screenshots**
> **Desktop (please complete the following information):**
> 
> * OS: macOS
> * Browser chrome?
> * Version Unknown
> 
> ## **Additional context**

@uehaj2022 
thank you very much for summarizing. Just one quick question, are galk-engineers invited to this repo ?

**Comment by uehaj2022** [comment]
@GochaLearningSpace still not. 
Could you invite them? (I don't know their github account)

**Comment by GochaLearningSpace** [comment]
> @GochaLearningSpace still not. I add you to members of this repository. If you accept the invitaion, I will permit to add members to this project. After that, please could you invite them? (I don't know their github account)

@uehaj2022 understood, please let me try.

**Comment by GochaLearningSpace** [comment]
> > @GochaLearningSpace still not. I add you to members of this repository. If you accept the invitaion, I will permit to add members to this project. After that, please could you invite them? (I don't know their github account)
> 
> @uehaj2022 understood, please let me try.

@uehaj2022 
 I tried to add engineers, but I could not find "Settings" tab, should I be able to add other members ?
